default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: ebdb
  username: root
  password: adminwebcomic
  host: aa1qdtcphorrge3.cuauwgcgclf0.eu-central-1.rds.amazonaws.com
  port: 3306
